---
- name: Configure Database servers
  hosts: rhel
  become: true

  vars:
    pgadmin_container:
      name: pgadmin
      image: docker.io/dpage/pgadmin4
      state: started
      volumes:
        - /etc/localtime:/etc/localtime:ro
      env:
        PGADMIN_DEFAULT_EMAIL: student@example.com
        PGADMIN_DEFAULT_PASSWORD: learn_ansible
      ports:
        - 8083:80
      log_options:
        max_size: 10

  tasks:
    - name: Install postgresql server package
      ansible.builtin.package:
        name: postgresql-server
        state: present


    # Do initial postgresql config & start the service & allow the traffic through the firewall
    - name: Do initial postgresql config
      ansible.builtin.command: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Start the service
      ansible.builtin.service:
        name: postgresql
        state: started

    - name: Allow the traffic through the firewall
      ansible.posix.firewalld:
        port: 5432/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Create podman container using pgadmin_container var
      containers.podman.podman_container:
        name: "{{ pgadmin_container.name }}"
        image: "{{ pgadmin_container.image }}"
        state: "{{ pgadmin_container.state }}"
        restart_policy: always
        ports: "{{ pgadmin_container.ports }}"
        env: "{{ pgadmin_container.env }}"
        volumes: "{{ pgadmin_container.volumes }}"
        log_options: "{{ pgadmin_container.log_options }}"
